version: '3'
services:
  mysql:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hansumDB
    ports:
      - "3306:3306"
    volumes:
      - ./my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
    networks:
      - test_network

  spring-boot-app:
# spring-boot-app build 파일 필요 시
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: hansumproject0522
    image : ukjang/hansumproject-spring-boot-app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hansumDB?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - test_network
networks:
  test_network: