name: Java CI with Gradle

# main 브랜치에 push 또는 PR 이벤트 발생 시 동작
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Java 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # 'adopt'를 사용할 수도 있음
        java-version: '17'
    
    # Gradle 설정
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # Spring Boot 어플리케이션 Build (1)
    - name: Spring Boot Build
      run: ./hansumproject/gradlew clean build --exclude-task test
    
    # Docker 이미지 Build (2)
    - name: Docker image build
      run: docker build -t ukjang/hansumproject-spring-boot-app .
    
    # DockerHub Login (3)
    - name: Docker login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Docker Hub push (4)
    - name: Docker Hub push
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ukjang/hansumproject-spring-boot-app --push .
